# Generated by Django 6.0.4 on 2026-04-09 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_product_name_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_new',
            field=models.BooleanField(default=False, verbose_name='Nouveauté'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_promo',
            field=models.BooleanField(default=False, verbose_name='En promotion'),
        ),
        migrations.AddField(
            model_name='product',
            name='promo_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Prix promo'),
        ),
    ]
